# Generated by Django 5.1.4 on 2024-12-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('icon', models.CharField(max_length=32, verbose_name='图表')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('name', models.CharField(max_length=32, verbose_name='路由名称')),
                ('is_menu', models.BooleanField(default=True, verbose_name='是否是菜单')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.folder', verbose_name='菜单目录')),
            ],
        ),
    ]
