# Generated by Django 5.1.4 on 2024-12-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permission_role_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
