# Generated by Django 5.1.4 on 2024-12-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
